src/_main/urls.py
from django.contrib import admin
from django.urls import path, include

from website import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls))
]

src/website/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views.settings import ProfileSetting
from .views.profile import ProfileView
from .views.website import WebSiteView

website = WebSiteView()
profile = ProfileView()
profile_setting = ProfileSetting()

app_name = "website"

urlpatterns = [
    path('', website.home, name="index"),
    path('about/', website.about, name="about"),
    path('contact/', website.contact, name="contact"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name="logout"),
    path('registration/', website.registration, name="registration"),

    # Auth profile route
    path('dashboard/', profile.dashboard, name='dashboard'),
    path('blog-posts/', profile.blog_posts, name='blog-posts'),
    path('comments/', profile.comments, name='comments'),
    path('profile/', profile.profile, name='profile'),
    path('update-profile/', profile.update_profile, name='update-profile'),

    # auth user setting
    path('settings/', auth_views.PasswordChangeView.as_view(template_name='dashboard/settings.html'), name='settings'),
   

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/website/models.py
from PIL import Image
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """User model."""
    email = models.EmailField('Email Address', unique=True)

    class Meta:
        db_table = 'auth_user'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self):
        super().save()
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            img.thumbnail((300, 300))
            img.save(self.image.path)


# Create your models here.
class Contact(models.Model):
    full_name = models.CharField(max_length=200)
    email_address = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=200)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

src/website/views.py
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

from .form.registration import UserRegisterForm
from .models import Contact
from .form.contact import ContactForm


class WebSiteView:
    # Create your views here.
    def home(self, request):

        return render(request, "index.html", {'home': True})

    def about(self, request):
        return render(request, "about.html", {})

    def contact(self, request):
        if request.method == 'POST':
            form = ContactForm(request.POST)
            if form.is_valid():
                # print(form.cleaned_data['full_name'])
                contact = Contact.objects.create(**form.cleaned_data)
                messages.success(request, 'Thank you')
                return redirect('/contact/')
        else:
            form = ContactForm()
            return render(request, "contact.html", {'form': form})

    def login(self, request):
        return render(request, "login.html", {})

    def registration(self, request):
        if request.method == 'POST':
            form = UserRegisterForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                messages.success(request, f'Account Created for {username}')
                return redirect('website:registration')
        else:
            form = UserRegisterForm()
        return render(request, "registration.html", {'form': form})

src/website/views/profile.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator

from ..form.settings import ChangeUsername
from ..form.settings import ChangeEmailAddress
from ..form.registration import ProfileUpdateForm
from ..form.registration import UserUpdateForm


class ProfileView:
    @method_decorator(login_required)
    def dashboard(self, request):
        return render(request, "dashboard/dashboard.html", {})

    @method_decorator(login_required)
    def blog_posts(self, request):
        return render(request, "dashboard/blog-posts.html", {})

    @method_decorator(login_required)
    def profile(self, request):
        return render(request, "dashboard/profile.html", {})

    @method_decorator(login_required)
    def update_profile(self, request):
        if request.method == 'POST':
            user_form = UserUpdateForm(request.POST, instance=request.user)
            profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
            if user_form.is_valid() and profile_form.is_valid():
                user_form.save()
                profile_form.save()
                messages.success(request, 'You account has been updated !')
                return redirect('website:profile')
        else:
            user_form = UserUpdateForm(instance=request.user)
            profile_form = ProfileUpdateForm(instance=request.user.profile)

        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }
        return render(request, 'dashboard/update-profile.html', context)

    @method_decorator(login_required)
    def comments(self, request):
        return render(request, "dashboard/comments.html", {})

src/website/views/settings.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_http_methods

from ..form.settings import ChangeEmailAddress, ChangeUsername


class ProfileSetting:

    @method_decorator(login_required)
    def settings(self, request):
        change_pass_form = PasswordChangeForm(request.user)
        return render(request, "dashboard/settings.html", {
            'change_pass_form': change_pass_form
        })

    @method_decorator(login_required)
    def change_username(self, request):
        return 0

    @method_decorator(login_required)
    def change_email(self, request):
        return 0

src/website/views/website.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator

from ..form.registration import UserRegisterForm
from ..models import Contact
from ..form.contact import ContactForm


class WebSiteView:
    # Create your views here.
    def home(self, request):
        return render(request, "index.html", {'home': True})

    def about(self, request):
        return render(request, "about.html", {})

    def contact(self, request):
        if request.method == 'POST':
            form = ContactForm(request.POST)
            if form.is_valid():
                # print(form.cleaned_data['full_name'])
                contact = Contact.objects.create(**form.cleaned_data)
                messages.success(request, 'Thank you')
                return redirect('/contact/')
        else:
            form = ContactForm()
            return render(request, "contact.html", {'form': form})

    def registration(self, request):
        if request.method == 'POST':
            form = UserRegisterForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                messages.success(request, f'Account Created for {username}')
                return redirect('website:registration')
        else:
            form = UserRegisterForm()
        return render(request, "registration.html", {'form': form})

src/templates/base_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Title {% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% include "partials/navbar.html" %}

{% block content %}


{% endblock %}

{% include "partials/footer.html" %}

<script src="{% static 'app.bundle.js' %}"></script>

</body>
</html>

src/templates/partials/footer.html
<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
            </div>
        </div>
    </div>
</footer>

src/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class=container><a class=navbar-brand href=#>Blocg</a>
        <button class=navbar-toggler type=button data-toggle=collapse data-target=#navbarSupportedContent
                aria-controls=navbarSupportedContent aria-expanded=false aria-label="Toggle navigation"><span
                class=navbar-toggler-icon></span></button>

        <div class="collapse navbar-collapse" id=navbarSupportedContent>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if home %} active {% endif %}">
                    <a class=nav-link href="{% url 'website:index' %}">Home</a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == "about" %} active {% endif %}">
                    <a class=nav-link href="{% url 'website:about' %}">About</a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == "contact" %} active {% endif %}">
                    <a class=nav-link href="{% url 'website:contact' %}">Contact</a>
                </li>
            </ul>
            <ul class=navbar-nav>
                {% if user.is_authenticated %}
                     <li class="nav-item {% if request.resolver_match.url_name == "login" %} active {% endif %}">
                        <a class=nav-link href="{% url 'website:profile' %}">Profile</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == "registration" %} active {% endif %}">
                        <a class=nav-link href="{% url 'website:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item {% if request.resolver_match.url_name == "login" %} active {% endif %}">
                        <a class=nav-link href="{% url 'website:login' %}">Login</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == "registration" %} active {% endif %}">
                        <a class=nav-link href="{% url 'website:registration' %}">Registration</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

src/website/templates/about.html
{% extends "base_layout.html" %}

{% block title %} About {% endblock %}

{% block content %}

    {% load static %}
    <section class=page>
        <div class=header><h2 class="m-title text-center">About Us <span>To contact us use the form bellow</span></h2>
        </div>

        <div class="container">
            <div class="row pt-5 pb-5">
                <div class="col-md-6">
                    <h3>About Us</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, amet consectetur culpa est
                        explicabo facere impedit, itaque maiores maxime modi nesciunt, pariatur recusandae sapiente sed
                        sit
                        temporibus tenetur velit vitae!</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid explicabo illo ipsum laudantium
                        nesciunt nobis omnis rem saepe tenetur voluptates! Alias cupiditate doloribus ipsum nostrum
                        ratione
                        sint tempora tempore voluptatibus.</p>
                </div>
                <div class="col-md-6">
                    <h3>About Us</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, amet consectetur culpa est
                        explicabo facere impedit, itaque maiores maxime modi nesciunt, pariatur recusandae sapiente sed
                        sit
                        temporibus tenetur velit vitae!</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid explicabo illo ipsum laudantium
                        nesciunt nobis omnis rem saepe tenetur voluptates! Alias cupiditate doloribus ipsum nostrum
                        ratione
                        sint tempora tempore voluptatibus.</p>
                </div>
            </div>
        </div>
    </section>

    <hr>


{% endblock %}

src/website/templates/contact.html
{% extends "base_layout.html" %}

{% block title %} Contact {% endblock %}

{% block content %}

    {% load static %}
    <section class=page>
        <div class=header><h2 class="m-title text-center">Contact Us <span>To contact us use the form bellow</span></h2>
        </div>
        <!-- Main Content -->
        <div class="container">
            <div class="row pt-5 pb-5">
                <div class="col-lg-8 col-md-10">


                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                <strong>Holy guacamole!</strong> You should check in on some of those fields below.
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form name="sentMessage" id="contactForm" action="{% url 'website:contact' %}" method="post">
                        {% csrf_token %}
                        <div class="control-group">
                            <div class="form-group floating-label-form-group controls">
                                {{ form.full_name.label_tag }}
                                {{ form.full_name }}
                                <p class="help-block text-danger">{{ form.full_name.errors }}</p>
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="form-group floating-label-form-group controls">
                                {{ form.email_address.label_tag }}
                                {{ form.email_address }}
                                <p class="help-block text-danger">{{ form.email_address.errors }}</p>
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                {{ form.phone_number.label_tag }}
                                {{ form.phone_number }}
                                <p class="help-block text-danger">{{ form.phone_number.errors }}</p>
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="form-group floating-label-form-group controls">
                                {{ form.message.label_tag }}
                                {{ form.message }}
                                <p class="help-block text-danger">{{ form.message.errors }}</p>
                            </div>
                        </div>
                        <br>
                        <div id="success"></div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <hr>


{% endblock %}

src/website/templates/dashboard/__sidebar.html
<div class="list-group">
    <a href="{% url 'website:dashboard' %}" class="list-group-item list-group-item-action {% if request.resolver_match.url_name == "dashboard" %} active {% endif %}">
        <i class="fas fa-tachometer-alt"></i> Dashboard
    </a>
    <a href="{% url 'website:blog-posts' %}" class="list-group-item list-group-item-action {% if request.resolver_match.url_name == "blog-posts" %} active {% endif %}">
        <i class="fas fa-blog"></i> Blog Post
    </a>
    <a href="{% url 'website:comments' %}" class="list-group-item list-group-item-action {% if request.resolver_match.url_name == "comments" %} active {% endif %}">
        <i class="fas fa-comments"></i> Comments
    </a>
    <a href="{% url 'website:profile' %}" class="list-group-item list-group-item-action {% if request.resolver_match.url_name == "profile" %} active {% endif %}">
        <i class="fas fa-user-cog"></i> Profile
    </a>
    <a href="{% url 'website:settings' %}" class="list-group-item list-group-item-action {% if request.resolver_match.url_name == "settings" %} active {% endif %}">
        <i class="fas fa-cogs"></i> Settings
    </a>
</div>

src/website/templates/dashboard/blog-posts.html
{% extends "base_layout.html" %}

{% block title %} Blog Posts  {% endblock %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <section class=page>
        <div class=header><h2 class="m-title text-center">Login <span>To contact us use the form bellow</span></h2>
        </div>
        <div class="container-fluid">
            <div class="row ">
                <div class="col-md-2">
                    {% include 'dashboard/__sidebar.html' %}
                </div>

                <div class="col-md-10">
                    <h2>Profile</h2>
                    <img src="{{ user.profile.image.url }}" class="img-fluid img-thumbnail" alt="">
                </div>
            </div>
        </div>
    </section>
    <br><br><br><br>
    <hr>
{% endblock %}

src/website/templates/dashboard/comments.html
{% extends "base_layout.html" %}

{% block title %} Comments  {% endblock %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <section class=page>
        <div class=header><h2 class="m-title text-center">Login <span>To contact us use the form bellow</span></h2>
        </div>
        <div class="container-fluid">
            <div class="row ">
                <div class="col-md-2">
                   {% include 'dashboard/__sidebar.html' %}
                </div>

                <div class="col-md-10">
                    <h2>Profile</h2>
                    <img src="{{ user.profile.image.url }}" class="img-fluid img-thumbnail" alt="">
                </div>
            </div>
        </div>
    </section>
    <br><br><br><br>
    <hr>
{% endblock %}

src/website/templates/dashboard/dashboard.html
{% extends "base_layout.html" %}

{% block title %} Dashboard  {% endblock %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <section class=page>
        <div class=header><h2 class="m-title text-center">Login <span>To contact us use the form bellow</span></h2>
        </div>
        <div class="container-fluid">
            <div class="row ">
                <div class="col-md-2">
                    {% include 'dashboard/__sidebar.html' %}
                </div>

                <div class="col-md-10">
                    <h2>Profile</h2>
                    <img src="{{ user.profile.image.url }}" class="img-fluid img-thumbnail" alt="">
                </div>
            </div>
        </div>
    </section>
    <br><br><br><br>
    <hr>
{% endblock %}

src/website/templates/dashboard/profile.html
{% extends "base_layout.html" %}

{% block title %} Profile  {% endblock %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <section class=page>
        <div class=header><h2 class="m-title text-center">My Profile <span>This is my profile</span></h2>
        </div>
        <div class="container-fluid">
            <div class="row ">
                <div class="col-md-2">
                    {% include 'dashboard/__sidebar.html' %}
                </div>

                <div class="col-md-10">
                    <div class="clearfix pt-2 pb-2">
                        <div class="float-left">
                            <h1>Profile</h1>
                        </div>

                        <a href="{% url 'website:update-profile' %}" class="btn btn-primary float-right">Update
                            Profile</a>
                    </div>

                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show"
                                         role="alert">
                                        <strong>Holy guacamole!</strong> {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>

                    <div class="row justify-content-center">

                        <div class="col-md-2">
                            <img src="{{ user.profile.image.url }}" class="img-fluid img-thumbnail" alt="">
                        </div>
                        <div class="col-md-4">
                            <h1>{{ user.first_name }} {{ user.last_name }}</h1>
                            <p>{{ user.email }}</p>
                            <p>{{ user.username }}</p>
                            <p>Status {% if user.is_active %} Active {% else %} InActive {% endif %}</p>
                            <p>Registered At : {{ user.date_joined }}</p>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </section>
    <br><br><br><br>
    <hr>
{% endblock %}

src/website/templates/dashboard/settings.html
{% extends "base_layout.html" %}

{% block title %} Settings  {% endblock %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <section class=page>
        <div class=header><h2 class="m-title text-center">Settings <span>To contact us use the form bellow</span></h2>
        </div>
        <div class="container-fluid">
            <div class="row ">
                <div class="col-md-2">
                    {% include 'dashboard/__sidebar.html' %}
                </div>

                <div class="col-md-10">
                    <div class="clearfix pt-2 pb-2">
                        <div class="float-left">
                            <h1>Settings</h1>
                        </div>

                        <a href="{% url 'website:update-profile' %}" class="btn btn-primary float-right">Update
                            Profile</a>
                    </div>

                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show"
                                         role="alert">
                                        <strong>Holy guacamole!</strong> {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>


                    <div class="row justify-content-center p-3">
                        <div class="col-md-12">
                            <ul class="nav nav-tabs">
                                <li class="nav-item">
                                    <a class="nav-link active" href="{% url 'website:settings' %}">Change Password</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Change Username</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Change Email</a>
                                </li>

                            </ul>
                        </div>

                        <div class="col-md-4 pt-5">
                            <form method="post" action=".">
                                {% csrf_token %}
                                <h3>Change Password</h3>
                                {{ form|crispy }}
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>


                    </div>

                </div>
            </div>
        </div>
    </section>
    <br><br><br><br>
    <hr>
{% endblock %}

src/website/templates/logout.html
{% extends "base_layout.html" %}

{% block title %} Login  {% endblock %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <section class=page>
        <div class=header><h2 class="m-title text-center">Log out <span>To contact us use the form bellow</span></h2>
        </div>
        <div class=container>
            <div class="row justify-content-md-center">
                <div class="col-md-6 mt-5">
                   <h2>You are logged out</h2>

                    <div class="border-top mt-5">
                        <small class="text-muted">Don't have an account ? <a
                                href="{% url 'website:login' %}">Login </a> </small>
                    </div>
                </div>

            </div>
        </div>
    </section>
    <br><br><br><br>
    <hr>
{% endblock %}

src/website/templates/registration.html
{% extends "base_layout.html" %}

{% block title %} Registration {% endblock %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <section class=page>
        <div class=header><h2 class="m-title text-center">Registration <span>To contact us use the form bellow</span>
        </h2>
        </div>
        <div class=container>
            <div class="row justify-content-md-center">
                <div class="col-md-6 mt-5">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                <strong>Holy guacamole!</strong> {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form class=mt-5 method="post" action=".">
                        {% csrf_token %}
                        <h3>Registration</h3>

                        <div class="form-row">
                            <div class="col-md-6">
                                {{ form.first_name|as_crispy_field }}
                            </div>
                            <div class="col-md-6">
                                {{ form.last_name|as_crispy_field }}
                            </div>
                        </div>

                        {{ form.username|as_crispy_field }}

                        {{ form.email|as_crispy_field }}
                        {{ form.password1|as_crispy_field }}
                        {{ form.password2|as_crispy_field }}

                        <button type=submit class="btn btn-primary">Sign Up</button>
                    </form>

                    <div class="border-top mt-5">
                        <small class="text-muted">Already has an account ? <a
                                href="{% url 'website:login' %}">Login </a> </small>
                    </div>

                </div>

            </div>
        </div>
    </section>
    <br><br><br><br>
    <hr>
{% endblock %}